@echo off
REM ============================================================================
REM   hash98-miner — one-click launcher
REM ----------------------------------------------------------------------------
REM   1. If .env is missing -> interactive wizard creates one.
REM   2. If target\release\hashminer.exe is missing -> cargo build --release.
REM   3. Show menu: run / dry-run / bench / devices / accounts / selftest.
REM ============================================================================
setlocal EnableDelayedExpansion
chcp 65001 >nul
cd /d "%~dp0"

REM ---------- step 1: .env wizard ----------
if not exist ".env" (
    echo.
    echo  ===========================================================
    echo   No .env found. Let's create one. Press Enter to keep blank.
    echo  ===========================================================
    echo.

    set /p _key="  Private key (0x...) [leave blank to use keys file]: "
    if "!_key!"=="" (
        set /p _kfile="  Path to keys file (one key per line) [keys.txt]: "
        if "!_kfile!"=="" set "_kfile=keys.txt"
    )

    set /p _rpc="  RPC URL [https://ethereum-rpc.publicnode.com]: "
    if "!_rpc!"=="" set "_rpc=https://ethereum-rpc.publicnode.com"

    set /p _ws="  WebSocket URL (optional): "

    set /p _devices="  GPU devices (all or e.g. 0,1) [all]: "
    if "!_devices!"=="" set "_devices=all"

    set /p _unroll="  Unroll [compact/full/auto/N] [compact]: "
    if "!_unroll!"=="" set "_unroll=compact"

    set /p _local="  Local work-group size [64]: "
    if "!_local!"=="" set "_local=64"

    set /p _dry="  Dry run? (true/false) [false]: "
    if "!_dry!"=="" set "_dry=false"

    > .env (
        echo # Generated by start.bat
        echo HASH98_PRIVATE_KEY=!_key!
        if defined _kfile echo HASH98_KEYS_FILE=!_kfile!
        echo HASH98_RPC_URL=!_rpc!
        echo HASH98_RPC_FALLBACKS=https://eth.llamarpc.com,https://rpc.ankr.com/eth,https://eth.drpc.org
        echo HASH98_WS_URL=!_ws!
        echo HASH98_GPU_DEVICES=!_devices!
        echo HASH98_UNROLL=!_unroll!
        echo HASH98_LOCAL_SIZE=!_local!
        echo HASH98_DRY_RUN=!_dry!
        echo HASH98_LOG_LEVEL=INFO
    )
    echo.
    echo  Wrote .env. You can edit it any time.
    echo.
)

REM ---------- step 2: build if missing ----------
set "BIN=target\release\hashminer.exe"
if not exist "%BIN%" (
    echo.
    echo  Binary not found — running: cargo build --release
    echo.
    where cargo >nul 2>&1
    if errorlevel 1 (
        echo  ERROR: Rust ^(cargo^) is not installed. Install from https://rustup.rs/
        pause
        exit /b 1
    )
    cargo build --release
    if errorlevel 1 (
        echo  Build failed.
        pause
        exit /b 1
    )
)

REM ---------- step 3: menu ----------
:menu
echo.
echo  ===== hash98-miner =====
echo    1. Run miner
echo    2. Dry-run (no broadcast)
echo    3. Bench
echo    4. List GPU devices
echo    5. Show accounts
echo    6. Self-test (kernel sanity check)
echo    Q. Quit
echo.
set /p _choice="  Choice: "
if /i "!_choice!"=="1" "%BIN%" run
if /i "!_choice!"=="2" "%BIN%" run --dry-run
if /i "!_choice!"=="3" "%BIN%" bench
if /i "!_choice!"=="4" "%BIN%" devices
if /i "!_choice!"=="5" "%BIN%" accounts
if /i "!_choice!"=="6" "%BIN%" selftest
if /i "!_choice!"=="q" goto :end
echo.
goto menu

:end
endlocal
